version: "3.9"

services:
  front-end:
    image: "arunsingh1801/front-end:v1"
    deploy:
      mode: global
      restart_policy:
        condition: on-failure
    networks:
      - infra-network
#    healthcheck:
#      test: curl -sS http://quotes:8081/ping || exit 1
#      interval: 5s
#      timeout: 10s
#      retries: 3
    ports:
      - target: 8080
        published: 8080
        protocol: tcp
        mode: host
    depends_on:
      - quotes
      - newsfeed
    environment:
      - APP_PORT=8080
      - STATIC_URL=http://0.0.0.0:8000
      - QUOTE_SERVICE_URL=http://quotes:8081
      - NEWSFEED_SERVICE_URL=http://newsfeed:8082
      - NEWSFEED_SERVICE_TOKEN=T1&eWbYXNWG1w1^YGKDPxAWJ@^et^&kX

  quotes:
    image: "arunsingh1801/quotes:v1"
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    networks:
      - infra-network
    environment:
      - APP_PORT=8081

  newsfeed:
    image: "arunsingh1801/newsfeed:v1"
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    networks:
      - infra-network
    environment:
      - APP_PORT=8082