version: "3.9"

services:
  nginx:
    image: nginx:1.18.0-alpine
    deploy:
      mode: global
      restart_policy:
        condition: on-failure
    configs:
      - source: nginx_config
        target: /etc/nginx/nginx.conf
        mode: 0755
    networks:
      - infra-network
    ports:
      - target: 8080
        published: 8080
        protocol: tcp
        mode: host
    depends_on:
      - front-end

  front-end:
    image: "arunsingh1801/front-end:v1"
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    networks:
      - infra-network
    depends_on:
      - quotes
      - newsfeed
    environment:
      APP_PORT: 8081
      STATIC_URL: https://infra-dev-s3.s3-eu-west-1.amazonaws.com
      QUOTE_SERVICE_URL: http://quotes:8082
      NEWSFEED_SERVICE_URL: http://newsfeed:8083
    secrets:
      - newsfeed_service_token

  quotes:
    image: "arunsingh1801/quotes:v1"
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    networks:
      - infra-network
    environment:
      - APP_PORT=8082
    secrets:
      - newsfeed_service_token

  newsfeed:
    image: "arunsingh1801/newsfeed:v1"
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    networks:
      - infra-network
    environment:
      - APP_PORT=8083
    secrets:
      - newsfeed_service_token
